export const GET_USER_PENDING = "GET_USER_PENDING";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";

export const GET_HISTORY_PENDING = "GET_HISTORY_PENDING";
export const GET_HISTORY_SUCCESS = "GET_HISTORY_SUCCESS";
export const GET_HISTORY_FAILED = "GET_HISTORY_FAILED";

export const GET_PRODUCTS_PENDING = "GET_PRODUCTS_PENDING";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";

export const REDEEM_POINTS_PENDING = "REDEEM_POINTS_PENDING";
export const REDEEM_POINTS_SUCCESS = "REDEEM_POINTS_SUCCESS";
export const REDEEM_POINTS_FAILED = "REDEEM_POINTS_FAILED ";

export const ADD_POINTS_PENDING = "ADD_POINTS_PENDING";
export const ADD_POINTS_SUCCESS = "ADD_POINTS_SUCCESS";
export const ADD_POINTS_FAILED = "ADD_POINTS_FAILED";

export const ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE";
export const ORDER_PRODUCTS_BY_CATEGORY = "ORDER_PRODUCTS_BY_CATEGORY";
